name: Build and Deploy to S3 and GCP
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - public/
      - docs/
      - .github/workflows/
  pull_request:
    branches: [ "main" ]
env:
  BUILD_DIR_NAME: dist
permissions:
  id-token: write
  contents: read

jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25"
          cache: "npm"

      - name: Disable Next.js telemetry
        run: echo "NEXT_TELEMETRY_DISABLED=1" >> $GITHUB_ENV

      - name: Cache Next.js build
        uses: actions/cache@v5
        with:
          path: |
            .next/cache
            node_modules/.cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{
            hashFiles('**.[jt]s', '**.[jt]sx', '**.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-nextjs-

      - run: npm ci
      - run: npm run build -- --webpack

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: build_files
          path: ${{env.BUILD_DIR_NAME}}

  deploy-s3:
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: build_files
          path: ./dist

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET}}/ \
            --delete \
            --exclude "images/*" \
            --exclude "documents/*"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{secrets.DISTRIBUTION_ID}} \
            --paths "${{secrets.INVALIDATION_PATH}}"

  deploy-gcp:
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: build_files
          path: ./dist

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        env:
          REGION: ${{ secrets.GCP_REGION }}
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME }}
          REGION: ${{ secrets.GCP_REGION }}
          REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
        run: |
          IMAGE_TAG="${REGION}-docker.pkg.dev/${GCP_PROJECT}/${REPOSITORY}/${IMAGE_NAME}:${{ github.sha }}"

          docker build -t ${IMAGE_TAG} .
          docker push ${IMAGE_TAG}

      - name: Deploy to Cloud Run
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME }}
          SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
          REGION: ${{ secrets.GCP_REGION }}
          REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
        run: |
          IMAGE_TAG="${REGION}-docker.pkg.dev/${GCP_PROJECT}/${REPOSITORY}/${IMAGE_NAME}:${{ github.sha }}"

          gcloud run deploy ${SERVICE_NAME} \
            --image ${IMAGE_TAG} \
            --platform managed \
            --region ${REGION} \
            --allow-unauthenticated \
            --project ${GCP_PROJECT}
